name: taski_challenger_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  flutter_svg: ^2.0.16
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  get_it: ^7.6.0
  hive_flutter: ^1.1.0

  i18n:
    path: "infrastructure/i18n"
  flutter_localization: ^0.3.1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  mocktail: ^1.0.4
  flutter_lints: ^5.0.0
  build_runner:
  flutter_gen_runner:

flutter_gen:
  output: lib/src/generated
  lineLength: 80`
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
